import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import NavTabs from "./NavTabs";
import FileDropzone from "./FileDropzone";
import DarkModeToggle from "./DarkModeToggle";
export default function Layout({ files, onUpload, error, onClearFiles, children, }) {
    const [sidebarOpen, setSidebarOpen] = useState(true);
    return (_jsxs("div", { className: "h-screen flex flex-col bg-gray-50 dark:bg-gray-900 overflow-hidden", children: [_jsx("header", { className: "bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 shadow-sm shrink-0", children: _jsxs("div", { className: "px-6 py-4 flex items-center justify-between", children: [_jsx("h1", { className: "text-xl font-bold text-blue-600 dark:text-blue-400", children: "PDF Tool" }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(DarkModeToggle, {}), files.length > 0 && (_jsxs("button", { onClick: onClearFiles, className: "text-sm text-gray-500 dark:text-gray-400 hover:text-red-600 dark:hover:text-red-400 transition-colors", children: ["Clear files (", files.length, ")"] }))] })] }) }), _jsx(NavTabs, {}), _jsxs("div", { className: "flex-1 flex flex-col md:flex-row min-h-0", children: [_jsxs("aside", { className: `${sidebarOpen ? "md:w-96" : "md:w-0"} shrink-0 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex flex-col min-h-0 transition-all duration-200 overflow-hidden`, children: [_jsx("div", { className: "flex items-center justify-end pt-2 pr-2 shrink-0", children: _jsx("button", { onClick: () => setSidebarOpen(false), className: "w-6 h-6 flex items-center justify-center rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors", title: "Close sidebar", children: "\u2715" }) }), _jsxs("div", { className: "p-5 pt-0 shrink-0", children: [_jsx(FileDropzone, { onUpload: onUpload }), error && (_jsx("div", { className: "mt-4 p-3 bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 rounded-lg text-red-700 dark:text-red-300 text-sm", children: error }))] })] }), !sidebarOpen && (_jsx("button", { onClick: () => setSidebarOpen(true), className: "shrink-0 w-6 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex items-center justify-center text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors cursor-pointer", title: "Open sidebar", children: "\u25B6" })), _jsx("main", { className: "flex-1 p-5 min-w-0 overflow-y-auto min-h-0", children: children })] })] }));
}
